version: "3"
services:
  node:
    image: node:carbon
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: "npm start"
